version: '3.8'

services:
  #database
  postdb:
    image: mcr.microsoft.com/mssql/server:2019-latest

#network section
networks:
  default: 
    name: blog_microservice  
    driver: bridge

#volume section
volumes:
  sqlserver_data:
    name: sqlserver_data  