version: '3.8'

services:

  postdb:
    container_name: postdb
    environment:
      SA_PASSWORD: "lupin2000!"
      ACCEPT_EULA: "Y"
    restart: always
    volumes:
     - sqlserver_data:/var/lib/sqlserver/data
    ports:
     - "1435:1433"
