version: '3.8'

services:
  #database
  postdb:
    image: mcr.microsoft.com/mssql/server:2019-latest

  notificationdb:
    image: mysql

  rabbitmq:
    image: rabbitmq:3-management-alpine

  chatdb:
    image: postgres

  userdb:
    image: mongo

#network section
networks:
  default: 
    name: blog_microservice  
    driver: bridge

#volume section
volumes:
  sqlserver_data:
    name: sqlserver_data  
  mysql_data:
    name: mysql_data  
  postgres_data:
    name: postgres_data  
  mongo_data:
    name: mongo_data  