version: '3.8'

services:

  postdb:
    container_name: postdb
    environment:
      SA_PASSWORD: "lupin2000!"
      ACCEPT_EULA: "Y"
    restart: always
    volumes:
     - sqlserver_data:/var/lib/sqlserver/data
    ports:
     - "1435:1433"

  notificationdb:
    container_name: notificationdb
    environment:
      MYSQL_ROOT_PASSWORD: lupin2000!
      MYSQL_DATABASE: NotiDb
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  chatdb:
    container_name: chatdb
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin1234
      - POSTGRES_DB=ChatDb
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  rabbitmq:
    container_name: rabbitmq
    restart: always
    ports:
       - "5672:5672"
       - "15672:15672"
